version: '3.8'

services:
  studybuddy:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Add your OpenAI API key here or use .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Object storage environment variables (if using)
      - PUBLIC_OBJECT_SEARCH_PATHS=${PUBLIC_OBJECT_SEARCH_PATHS}
      - PRIVATE_OBJECT_DIR=${PRIVATE_OBJECT_DIR}
      - DEFAULT_OBJECT_STORAGE_BUCKET_ID=${DEFAULT_OBJECT_STORAGE_BUCKET_ID}
    volumes:
      # Persist data (if using file-based storage)
      - studybuddy-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Memory limits for Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  studybuddy-data:
    driver: local