version: '3.8'

# Standard Docker volume configuration (alternative to bind mount)
# Use this if you prefer Docker-managed volumes over bind mounts
# To use: docker-compose -f docker-compose.standard.yml up -d

services:
  studybuddy:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=studybuddy
      - POSTGRES_USER=studybuddy
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-studybuddy123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studybuddy"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    # Docker-managed volume (stored in /var/lib/docker/volumes/)