services:
  studybuddy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: "production"
      PORT: "5000"
      PGHOST: "postgres"
      PGPORT: "5432"
      PGUSER: "user"
      PGPASSWORD: "password"
      PGDATABASE: "studybuddy"
      OPENAI_API_KEY: "${OPENAI_API_KEY}" 
      # Optional: stop dev WS/HTTPS calls to localhost:443
      ENABLE_WEBSOCKET: "false"
      # Or, if you actually use a WS/HTTP endpoint, set:
      # ORIGIN: "http://studybuddy:5000"
      # WS_URL: "ws://studybuddy:5000/v2"
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "studybuddy"
    ports:
      - "5439:5432"  # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
